// Compiled by ClojureScript 1.10.439 {:static-fns true, :optimize-constants true}
goog.provide('re_demo.checkbox');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('re_com.core');
goog.require('re_com.misc');
goog.require('re_demo.utils');
goog.require('reagent.core');
re_demo.checkbox.right_arrow = (function re_demo$checkbox$right_arrow(){
return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$svg,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$height,(20),cljs.core.cst$kw$width,(25)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$line,new cljs.core.PersistentArrayMap(null, 5, [cljs.core.cst$kw$x1,"0",cljs.core.cst$kw$y1,"10",cljs.core.cst$kw$x2,"20",cljs.core.cst$kw$y2,"10",cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$stroke,"#888"], null)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$polygon,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$points,"20,6 20,14 25,10",cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$stroke,"#888",cljs.core.cst$kw$fill,"#888"], null)], null)], null)], null);
});
re_demo.checkbox.left_arrow = (function re_demo$checkbox$left_arrow(){
return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$svg,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$height,(20),cljs.core.cst$kw$width,(25)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$line,new cljs.core.PersistentArrayMap(null, 5, [cljs.core.cst$kw$x1,"5",cljs.core.cst$kw$y1,"10",cljs.core.cst$kw$x2,"20",cljs.core.cst$kw$y2,"10",cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$stroke,"#888"], null)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$polygon,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$points,"5,6 5,14 0,10",cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$stroke,"#888",cljs.core.cst$kw$fill,"#888"], null)], null)], null)], null);
});
re_demo.checkbox.checkboxes_demo = (function re_demo$checkbox$checkboxes_demo(){
var disabled_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var ticked_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var something1_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var something2_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(true);
var all_for_one_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(true);
return ((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (){
return new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$size,"auto",cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.panel_title,"[checkbox ... ]","src/re_com/misc.cljs","src/re_demo/checkbox.cljs"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"100px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$width,"450px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Notes"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.status_text,"Stable"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"A boostrap-styled checkbox, with optional label (always displayed to the right)."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Clicking on the label is the same as clicking on the checkbox."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.args_table,re_com.misc.checkbox_args_desc], null)], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Demo"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"15px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$height,"20px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,"tick me  ",cljs.core.cst$kw$model,ticked_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11736_SHARP_){
return cljs.core.reset_BANG_(ticked_QMARK_,p1__11736_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
], null),(cljs.core.truth_(cljs.core.deref(ticked_QMARK_))?new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.checkbox.left_arrow], null):null),(cljs.core.truth_(cljs.core.deref(ticked_QMARK_))?new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.label,cljs.core.cst$kw$label," is ticked"], null):null)], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"1px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$model,all_for_one_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11737_SHARP_){
return cljs.core.reset_BANG_(all_for_one_QMARK_,p1__11737_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$model,all_for_one_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11738_SHARP_){
return cljs.core.reset_BANG_(all_for_one_QMARK_,p1__11738_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$model,all_for_one_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11739_SHARP_){
return cljs.core.reset_BANG_(all_for_one_QMARK_,p1__11739_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
,cljs.core.cst$kw$label,"all for one, and one for all.  "], null)], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"15px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,"tick this one, to \"disable\"",cljs.core.cst$kw$model,disabled_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11740_SHARP_){
return cljs.core.reset_BANG_(disabled_QMARK_,p1__11740_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.checkbox.right_arrow], null),new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,(cljs.core.truth_(cljs.core.deref(disabled_QMARK_))?"now disabled":"enabled"),cljs.core.cst$kw$model,something1_QMARK_,cljs.core.cst$kw$disabled_QMARK_,disabled_QMARK_,cljs.core.cst$kw$label_DASH_style,(cljs.core.truth_(cljs.core.deref(disabled_QMARK_))?new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$color,"#888"], null):null),cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11741_SHARP_){
return cljs.core.reset_BANG_(something1_QMARK_,p1__11741_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
], null)], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"1px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$model,something2_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_){
return (function (p1__11742_SHARP_){
return cljs.core.reset_BANG_(something2_QMARK_,p1__11742_SHARP_);
});})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.gap,cljs.core.cst$kw$size,"50px"], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.checkbox.left_arrow], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.gap,cljs.core.cst$kw$size,"5px"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.label,cljs.core.cst$kw$label,"no label on this one"], null)], null)], null)], null)], null)], null)], null)], null)], null)], null)], null);
});
;})(disabled_QMARK_,ticked_QMARK_,something1_QMARK_,something2_QMARK_,all_for_one_QMARK_))
});
re_demo.checkbox.panel = (function re_demo$checkbox$panel(){
return new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.checkbox.checkboxes_demo], null);
});
