// Compiled by ClojureScript 1.10.439 {:static-fns true, :optimize-constants true}
goog.provide('re_demo.input_time');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('re_com.core');
goog.require('re_com.input_time');
goog.require('re_demo.utils');
goog.require('reagent.core');
re_demo.input_time.simulated_bools = (function re_demo$input_time$simulated_bools(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_){
return new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"20px",cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"15px",cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":disabled?"], null)], null),cljs.core.cst$kw$model,cljs.core.deref(disabled_QMARK_),cljs.core.cst$kw$on_DASH_change,(function (p1__11526_SHARP_){
return cljs.core.reset_BANG_(disabled_QMARK_,p1__11526_SHARP_);
})], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":hide-border?"], null)], null),cljs.core.cst$kw$model,cljs.core.deref(hide_border_QMARK_),cljs.core.cst$kw$on_DASH_change,(function (p1__11527_SHARP_){
return cljs.core.reset_BANG_(hide_border_QMARK_,p1__11527_SHARP_);
})], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":show-icon?"], null)], null),cljs.core.cst$kw$model,cljs.core.deref(show_icon_QMARK_),cljs.core.cst$kw$on_DASH_change,(function (p1__11528_SHARP_){
return cljs.core.reset_BANG_(show_icon_QMARK_,p1__11528_SHARP_);
})], null)], null)], null)], null)], null);
});
re_demo.input_time.basics_demo = (function re_demo$input_time$basics_demo(){
var disabled_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var hide_border_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var show_icon_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(true);
var an_int_time = reagent.core.atom.cljs$core$IFn$_invoke$arity$1((900));
var init_minimum = (0);
var minimum = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(init_minimum);
var init_maximum = (2359);
var maximum = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(init_maximum);
return ((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (){
return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Demo"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$p,"There are two instances of this component below."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$p,"The first one is the default size."], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$p,"The second one specifies ",new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":style {:font-size \"11px\"}"], null)," to make a smaller version."], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.gap,cljs.core.cst$kw$size,"20px"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$width,"140px",cljs.core.cst$kw$gap,"30px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 15, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.input_time,cljs.core.cst$kw$model,an_int_time,cljs.core.cst$kw$minimum,cljs.core.deref(minimum),cljs.core.cst$kw$maximum,cljs.core.deref(maximum),cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (p1__11529_SHARP_){
return cljs.core.reset_BANG_(an_int_time,p1__11529_SHARP_);
});})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
,cljs.core.cst$kw$disabled_QMARK_,disabled_QMARK_,cljs.core.cst$kw$hide_DASH_border_QMARK_,cljs.core.deref(hide_border_QMARK_),cljs.core.cst$kw$show_DASH_icon_QMARK_,cljs.core.deref(show_icon_QMARK_)], null),new cljs.core.PersistentVector(null, 17, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.input_time,cljs.core.cst$kw$model,an_int_time,cljs.core.cst$kw$minimum,cljs.core.deref(minimum),cljs.core.cst$kw$maximum,cljs.core.deref(maximum),cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (p1__11530_SHARP_){
return cljs.core.reset_BANG_(an_int_time,p1__11530_SHARP_);
});})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
,cljs.core.cst$kw$disabled_QMARK_,disabled_QMARK_,cljs.core.cst$kw$hide_DASH_border_QMARK_,cljs.core.deref(hide_border_QMARK_),cljs.core.cst$kw$show_DASH_icon_QMARK_,cljs.core.deref(show_icon_QMARK_),cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$font_DASH_size,"11px"], null)], null)], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 9, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.title,cljs.core.cst$kw$level,cljs.core.cst$kw$level3,cljs.core.cst$kw$label,"Parameters"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.input_time.simulated_bools,disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.gap,cljs.core.cst$kw$size,"20px"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.title,cljs.core.cst$kw$level,cljs.core.cst$kw$level3,cljs.core.cst$kw$label,"Model resets"], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.button,cljs.core.cst$kw$label,"11am",cljs.core.cst$kw$class,"btn btn-default",cljs.core.cst$kw$on_DASH_click,((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (){
return cljs.core.reset_BANG_(an_int_time,(1100));
});})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.button,cljs.core.cst$kw$label,"5pm",cljs.core.cst$kw$class,"btn btn-default",cljs.core.cst$kw$on_DASH_click,((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (){
return cljs.core.reset_BANG_(an_int_time,(1700));
});})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
], null)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.gap,cljs.core.cst$kw$size,"20px"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.title,cljs.core.cst$kw$level,cljs.core.cst$kw$level3,cljs.core.cst$kw$label,"Simulated minimum & maximum changes"], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.label,cljs.core.cst$kw$label,":minimum"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.label,cljs.core.cst$kw$label,cljs.core.deref(minimum),cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$width,"40px",cljs.core.cst$kw$font_DASH_size,"11px",cljs.core.cst$kw$text_DASH_align,"center"], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.label,cljs.core.cst$kw$label,":maximum"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.label,cljs.core.cst$kw$label,cljs.core.deref(maximum),cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$width,"40px",cljs.core.cst$kw$font_DASH_size,"11px",cljs.core.cst$kw$text_DASH_align,"center"], null)], null)], null)], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":minimum 10am"], null)], null),cljs.core.cst$kw$model,cljs.core.not_EQ_.cljs$core$IFn$_invoke$arity$2(cljs.core.deref(minimum),init_minimum),cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (p1__11531_SHARP_){
return cljs.core.reset_BANG_(minimum,(cljs.core.truth_(p1__11531_SHARP_)?(1000):init_minimum));
});})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":maximum 2pm"], null)], null),cljs.core.cst$kw$model,cljs.core.not_EQ_.cljs$core$IFn$_invoke$arity$2(cljs.core.deref(maximum),init_maximum),cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum){
return (function (p1__11532_SHARP_){
return cljs.core.reset_BANG_(maximum,(cljs.core.truth_(p1__11532_SHARP_)?(1400):init_maximum));
});})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
], null)], null)], null)], null)], null)], null)], null)], null)], null);
});
;})(disabled_QMARK_,hide_border_QMARK_,show_icon_QMARK_,an_int_time,init_minimum,minimum,init_maximum,maximum))
});
re_demo.input_time.panel2 = (function re_demo$input_time$panel2(){
return new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$size,"auto",cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.panel_title,"[input-time ... ]","src/re_com/input_time.cljs","src/re_demo/input_time.cljs"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"100px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$width,"450px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Notes"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.status_text,"Stable"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Allows the user to input time in 24hr format."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Filters out all keystrokes other than numbers and ':'. Attempts to limit input to valid values.\n                                            Provides interpretation of incomplete input, for example '123' is interpretted as '1:23'."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"If the user exits the input field with an invalid value, it will be replaced with the last known valid value."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.args_table,re_com.input_time.input_time_args_desc], null)], null)], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.input_time.basics_demo], null)], null)], null)], null)], null);
});
re_demo.input_time.panel = (function re_demo$input_time$panel(){
return new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.input_time.panel2], null);
});
