// Compiled by ClojureScript 1.10.439 {:static-fns true, :optimize-constants true}
goog.provide('re_demo.selection_list');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('re_com.core');
goog.require('re_com.selection_list');
goog.require('re_demo.utils');
goog.require('reagent.core');
re_demo.selection_list.options_with = (function re_demo$selection_list$options_with(width,content,multi_select_QMARK_,disabled_QMARK_,required_QMARK_,as_exclusions_QMARK_){
return (function (){
return new cljs.core.PersistentVector(null, 9, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$width,[cljs.core.str.cljs$core$IFn$_invoke$arity$1(width),"px"].join(''),cljs.core.cst$kw$gap,"20px",cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Demo"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.title,cljs.core.cst$kw$level,cljs.core.cst$kw$level3,cljs.core.cst$kw$label,"Parameters"], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"15px",cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":disabled?"], null)], null),cljs.core.cst$kw$model,disabled_QMARK_,cljs.core.cst$kw$on_DASH_change,(function (p1__11745_SHARP_){
return cljs.core.reset_BANG_(disabled_QMARK_,p1__11745_SHARP_);
})], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":multi-select?"], null)], null),cljs.core.cst$kw$model,multi_select_QMARK_,cljs.core.cst$kw$on_DASH_change,(function (p1__11746_SHARP_){
return cljs.core.reset_BANG_(multi_select_QMARK_,p1__11746_SHARP_);
})], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":required?"], null)], null),cljs.core.cst$kw$model,required_QMARK_,cljs.core.cst$kw$on_DASH_change,(function (p1__11747_SHARP_){
return cljs.core.reset_BANG_(required_QMARK_,p1__11747_SHARP_);
})], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":as-exclusions?"], null)], null),cljs.core.cst$kw$model,as_exclusions_QMARK_,cljs.core.cst$kw$on_DASH_change,(function (p1__11748_SHARP_){
return cljs.core.reset_BANG_(as_exclusions_QMARK_,p1__11748_SHARP_);
})], null)], null)], null),content], null)], null);
});
});
re_demo.selection_list.list_with_options = (function re_demo$selection_list$list_with_options(width){
var disabled_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var multi_select_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(true);
var required_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(true);
var as_exclusions_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
var items = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(new cljs.core.PersistentVector(null, 8, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"1",cljs.core.cst$kw$label,"1st RULE: You do not talk about FIGHT CLUB.",cljs.core.cst$kw$short,"1st RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"2",cljs.core.cst$kw$label,"2nd RULE: You DO NOT talk about FIGHT CLUB.",cljs.core.cst$kw$short,"2nd RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"3",cljs.core.cst$kw$label,"3rd RULE: If someone says \"stop\" or goes limp, taps out the fight is over.",cljs.core.cst$kw$short,"3rd RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"4",cljs.core.cst$kw$label,"4th RULE: Only two guys to a fight.",cljs.core.cst$kw$short,"4th RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"5",cljs.core.cst$kw$label,"5th RULE: One fight at a time.",cljs.core.cst$kw$short,"5th RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"6",cljs.core.cst$kw$label,"6th RULE: No shirts, no shoes.",cljs.core.cst$kw$short,"6th RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"7",cljs.core.cst$kw$label,"7th RULE: Fights will go on as long as they have to.",cljs.core.cst$kw$short,"7th RULE"], null),new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$id,"8",cljs.core.cst$kw$label,"8th RULE: If this is your first night at FIGHT CLUB, you HAVE to fight.",cljs.core.cst$kw$short,"8th RULE"], null)], null));
var selections = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(cljs.core.set(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["2"], null)));
return new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.selection_list.options_with,width,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 21, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.selection_list,cljs.core.cst$kw$width,"391px",cljs.core.cst$kw$max_DASH_height,"95px",cljs.core.cst$kw$model,selections,cljs.core.cst$kw$choices,items,cljs.core.cst$kw$label_DASH_fn,cljs.core.cst$kw$label,cljs.core.cst$kw$as_DASH_exclusions_QMARK_,as_exclusions_QMARK_,cljs.core.cst$kw$multi_DASH_select_QMARK_,multi_select_QMARK_,cljs.core.cst$kw$disabled_QMARK_,disabled_QMARK_,cljs.core.cst$kw$required_QMARK_,required_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (disabled_QMARK_,multi_select_QMARK_,required_QMARK_,as_exclusions_QMARK_,items,selections){
return (function (p1__11749_SHARP_){
return cljs.core.reset_BANG_(selections,p1__11749_SHARP_);
});})(disabled_QMARK_,multi_select_QMARK_,required_QMARK_,as_exclusions_QMARK_,items,selections))
], null)], null)], null),multi_select_QMARK_,disabled_QMARK_,required_QMARK_,as_exclusions_QMARK_], null);
});
re_demo.selection_list.panel2 = (function re_demo$selection_list$panel2(){
return new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$size,"auto",cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.panel_title,"[selection-list ... ]","src/re_com/selection_list.cljs","src/re_demo/selection_list.cljs"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"100px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$width,"450px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Notes"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.status_text,"Stable"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Allows the user to select items from a list (single or multi)."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Uses radio buttons when single selecting, and checkboxes when multi-selecting."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Via strike-through, it supports the notion of selections representing exclusions, rather than inclusions."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.args_table,re_com.selection_list.selection_list_args_desc], null)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.selection_list.list_with_options,(600)], null)], null)], null)], null)], null);
});
re_demo.selection_list.panel = (function re_demo$selection_list$panel(){
return new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.selection_list.panel2], null);
});
