// Compiled by ClojureScript 1.10.439 {:static-fns true, :optimize-constants true}
goog.provide('re_demo.slider');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('re_com.core');
goog.require('re_com.misc');
goog.require('re_demo.utils');
goog.require('reagent.core');
re_demo.slider.slider_demo = (function re_demo$slider$slider_demo(){
var slider_val = reagent.core.atom.cljs$core$IFn$_invoke$arity$1("0");
var slider_min = reagent.core.atom.cljs$core$IFn$_invoke$arity$1("0");
var slider_max = reagent.core.atom.cljs$core$IFn$_invoke$arity$1("100");
var slider_step = reagent.core.atom.cljs$core$IFn$_invoke$arity$1("1");
var disabled_QMARK_ = reagent.core.atom.cljs$core$IFn$_invoke$arity$1(false);
return ((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (){
return new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$size,"auto",cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.panel_title,"[slider ... ]","src/re_com/misc.cljs","src/re_demo/slider.cljs"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"100px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$width,"450px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Notes"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.status_text,"Stable"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.p,"Standard HTML5 slider control."], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.args_table,re_com.misc.slider_args_desc], null)], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.utils.title2,"Demo"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.v_box,cljs.core.cst$kw$gap,"20px",cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 8, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 15, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.slider,cljs.core.cst$kw$model,slider_val,cljs.core.cst$kw$min,slider_min,cljs.core.cst$kw$max,slider_max,cljs.core.cst$kw$step,slider_step,cljs.core.cst$kw$width,"300px",cljs.core.cst$kw$on_DASH_change,((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (p1__11727_SHARP_){
return cljs.core.reset_BANG_(slider_val,cljs.core.str.cljs$core$IFn$_invoke$arity$1(p1__11727_SHARP_));
});})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
,cljs.core.cst$kw$disabled_QMARK_,disabled_QMARK_], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.gap,cljs.core.cst$kw$size,"0px"], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.title,cljs.core.cst$kw$level,cljs.core.cst$kw$level3,cljs.core.cst$kw$label,"Parameters"], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":model"], null)], null),new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.input_text,cljs.core.cst$kw$model,slider_val,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$height,"26px",cljs.core.cst$kw$on_DASH_change,((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (p1__11728_SHARP_){
return cljs.core.reset_BANG_(slider_val,p1__11728_SHARP_);
});})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
,cljs.core.cst$kw$change_DASH_on_DASH_blur_QMARK_,false], null)], null)], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":min"], null)], null),new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.input_text,cljs.core.cst$kw$model,slider_min,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$height,"26px",cljs.core.cst$kw$on_DASH_change,((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (p1__11729_SHARP_){
return cljs.core.reset_BANG_(slider_min,p1__11729_SHARP_);
});})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
,cljs.core.cst$kw$change_DASH_on_DASH_blur_QMARK_,false], null)], null)], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":max"], null)], null),new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.input_text,cljs.core.cst$kw$model,slider_max,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$height,"26px",cljs.core.cst$kw$on_DASH_change,((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (p1__11730_SHARP_){
return cljs.core.reset_BANG_(slider_max,p1__11730_SHARP_);
});})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
,cljs.core.cst$kw$change_DASH_on_DASH_blur_QMARK_,false], null)], null)], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.h_box,cljs.core.cst$kw$gap,"10px",cljs.core.cst$kw$align,cljs.core.cst$kw$center,cljs.core.cst$kw$children,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":step"], null)], null),new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.input_text,cljs.core.cst$kw$model,slider_step,cljs.core.cst$kw$width,"60px",cljs.core.cst$kw$height,"26px",cljs.core.cst$kw$on_DASH_change,((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (p1__11731_SHARP_){
return cljs.core.reset_BANG_(slider_step,p1__11731_SHARP_);
});})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
,cljs.core.cst$kw$change_DASH_on_DASH_blur_QMARK_,false], null)], null)], null),new cljs.core.PersistentVector(null, 7, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.checkbox,cljs.core.cst$kw$label,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_com.core.box,cljs.core.cst$kw$align,cljs.core.cst$kw$start,cljs.core.cst$kw$child,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$code,":disabled?"], null)], null),cljs.core.cst$kw$model,disabled_QMARK_,cljs.core.cst$kw$on_DASH_change,((function (slider_val,slider_min,slider_max,slider_step,disabled_QMARK_){
return (function (val){
return cljs.core.reset_BANG_(disabled_QMARK_,val);
});})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
], null)], null)], null)], null)], null)], null)], null)], null)], null);
});
;})(slider_val,slider_min,slider_max,slider_step,disabled_QMARK_))
});
re_demo.slider.panel = (function re_demo$slider$panel(){
return new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [re_demo.slider.slider_demo], null);
});
